name: Perseus Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build Perseus APK
        run: ./patch_perseus.sh

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh
                    
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Perseus Release"
          files: |
            build/*.apk
